dbfilename redis_queue.rdb
dir /home/korecent/korecent_training/final_training_assgn/contract-management/frappe-bench/config/pids
pidfile /home/korecent/korecent_training/final_training_assgn/contract-management/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/korecent/korecent_training/final_training_assgn/contract-management/frappe-bench/config/redis_queue.acl
